Repository rauc/meta-rauc, pull requests merged in 2018-12, with the labels that each got.

#51 rauc: add rauc-mark-good support for SysVinit
  recipes-core/rauc/files/rauc-mark-good.init
  recipes-core/rauc/rauc-target.inc
Labels: enhancement, master

#52 two small bundle.bbclass tweaks
  classes/bundle.bbclass
Labels: bug, master, thud

#58 do not use {S}ource dir as bundle contents dir
  classes/bundle.bbclass
Labels: master, thud

#62 Support for RAUC v1.0
  recipes-core/rauc/nativesdk-rauc_0.3.bb
  recipes-core/rauc/nativesdk-rauc_0.4.bb
  recipes-core/rauc/nativesdk-rauc_1.0.bb
  recipes-core/rauc/rauc-0.3.inc
  recipes-core/rauc/rauc-0.4.inc
  recipes-core/rauc/rauc-1.0.inc
  recipes-core/rauc/rauc-git.inc
  recipes-core/rauc/rauc-native_0.3.bb
  recipes-core/rauc/rauc-native_1.0.bb
  recipes-core/rauc/rauc_0.3.bb
  recipes-core/rauc/rauc_1.0.bb
Labels: master, thud, version bump
