Repository rauc/meta-rauc, pull requests merged in 2020-04, with the labels that each got.

#115 Add recipe for rauc-hawkbit-updater
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb
Labels: enhancement, master

#121 rauc: update to v1.3
  recipes-core/rauc/nativesdk-rauc_1.2.bb
  recipes-core/rauc/nativesdk-rauc_1.3.bb
  recipes-core/rauc/rauc-1.3.inc
  recipes-core/rauc/rauc-native_1.3.bb
  recipes-core/rauc/rauc-target.inc
  recipes-core/rauc/rauc.inc
  recipes-core/rauc/rauc_1.3.bb
Labels: master, version bump

#99 zstd: remove recipe from layer in favor of its meta-oe version
  recipes-support/zstd/zstd_git.bb
Labels: master

#74 rauc-mark-good.service: leverage systemd's sync target
  recipes-core/rauc/files/rauc-mark-good.service
Labels: enhancement
