Repository rauc/meta-rauc, pull requests merged in 2020-09, with the labels that each got.

#108 rauc-hawkbit: Add systemd service
  recipes-support/rauc-hawkbit/files/rauc-hawkbit.service
  recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb
Labels: enhancement

#132 rauc-hawkbit: Update to latest release 0.2.0
  recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb
Labels: version bump

#144 classes: bundle: Fix typo "CONVERTS_ARGS"
  classes/bundle.bbclass
Labels: documentation

#143 classes: bundle: add hook to SRC_URI in example
  classes/bundle.bbclass
Labels: documentation

#142 Convert REAMDE to rst and update some chapters
  README
  README.rst
Labels: documentation
