Repository rauc/meta-rauc, pull requests merged in 2020-10, with the labels that each got.

#146 rauc: rauc-service has a runtime dependency on dbus
  recipes-core/rauc/rauc.inc
Labels: enhancement

#148 classes: bundle: Avoid using img_fstype from previous iteration
  classes/bundle.bbclass
Labels: bug, master

#151 busybox: add patch to support 'sizelimit' and 'offset' option for lo
  recipes-core/busybox/busybox_%.bbappend
  recipes-core/busybox/files/0001-mount-support-the-sizelimit-and-offset-option-for-lo.patch
Labels: master

#152 conf: layer: add 'gatesgarth' to LAYERSERIES_COMPAT
  conf/layer.conf
Labels: master

#153 bundle.bbclass: fixes for collecting artifacts
  classes/bundle.bbclass
Labels: bug

#154 classes: bundle: add WORKDIR also to regular image search space
  classes/bundle.bbclass
Labels: enhancement
