Repository rauc/meta-rauc, pull requests merged in 2020-07, with the labels that each got.

#123 rauc: fix RRECOMMENDS for rauc-native -> squashfs-tools-native
  recipes-core/rauc/rauc-native.inc
  recipes-core/rauc/rauc-target.inc
  recipes-core/rauc/rauc.inc
Labels: bug

#129 classes: bundle: Add option to build casync bundle
  classes/bundle.bbclass
Labels: enhancement

#131 rauc-hawkbit-updater: Add user rauc-hawkbit
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb
Labels: bug, master

#134 bundle: Remove the do_package_write_* tasks
  classes/bundle.bbclass
Labels: bug
