Repository rauc/meta-rauc, pull requests merged in 2020-03, with the labels that each got.

#116 rauc: fix upstream version check
  recipes-core/rauc/rauc-1.2.inc
Labels: enhancement

#119 conf: layer.conf: python3-yarl bbappend requires meta-python
  conf/layer.conf
Labels: zeus

#120 conf: layer: add 'dunfell' to LAYERSERIES_COMPAT
  conf/layer.conf
Labels: dunfell, master
