Repository rauc/meta-rauc, pull requests merged in 2020-11, with the labels that each got.

#156 rauc: add 'gpt' to PACKAGECONFIG
  recipes-core/rauc/rauc-target.inc
  recipes-core/rauc/rauc.inc
Labels: enhancement

#155 bundle: Add slot parameter for bootloader offset
  classes/bundle.bbclass
Labels: enhancement

#160 README.rst: add license and CI builder badge
  README.rst
Labels: documentation, testing

#158 Update rauc-hawkbit-updater_git.bb
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb
Labels: version bump

#163 classes: bundle: use fatal() instead of FuncFailed
  classes/bundle.bbclass
Labels: backport candidate, bug
