Repository rauc/meta-rauc, pull requests merged in 2021-08, with the labels that each got.

#196 Cherrypick RAUC_BUNDLE_EXTRA_DEPENDS fix to dunfell
  classes/bundle.bbclass
Labels: dunfell

#195 convert to new override syntax
  .github/workflows/meta-rauc.yml
  README.rst
  conf/layer.conf
  recipes-bsp/dt-utils/dt-utils.inc
  recipes-casync/casync/casync_git.bb
  recipes-core/bundles/core-bundle-minimal.bb
  recipes-core/busybox/busybox_rauc.inc
  recipes-core/packagegroups/packagegroup-base_rauc.inc
  recipes-core/rauc/files/system.conf
  recipes-core/rauc/rauc-native.inc
  recipes-core/rauc/rauc-target.inc
  recipes-core/rauc/rauc.inc
  recipes-devtools/python-gbulb/python3-gbulb_0.6.1.bb
  recipes-kernel/linux/linux-yocto_rauc.inc
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb
  recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb
  scripts/README
Labels: master

#197 rauc: rauc-mark-good: improve service unit
  recipes-core/rauc/files/rauc-mark-good.service
Labels: enhancement
