Repository rauc/meta-rauc, pull requests merged in 2022-10, with the labels that each got.

#240 rauc: update to 1.8
  recipes-core/rauc/nativesdk-rauc_1.8.bb
  recipes-core/rauc/rauc-1.8.inc
  recipes-core/rauc/rauc-native_1.8.bb
  recipes-core/rauc/rauc_1.8.bb
Labels: version bump, backport candidate

#244 rauc-hawkbit-updater: update to v1.2
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.2.bb
Labels: version bump

#245 Update rauc-hawkbit-updater to v1.2
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.2.bb
Labels: dunfell

#248 classes: bundle: allow skipping bytes from image
  classes/bundle.bbclass
Labels: enhancement, master
