Repository rauc/meta-rauc, pull requests merged in 2022-02, with the labels that each got.

#212 rauc-hawkbit-updater: update to v1.1
  recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.1.bb
Labels: version bump

#216 rauc: update to 1.6
  recipes-core/rauc/nativesdk-rauc_1.5.1.bb
  recipes-core/rauc/nativesdk-rauc_1.6.bb
  recipes-core/rauc/rauc-1.6.inc
  recipes-core/rauc/rauc-native_1.6.bb
  recipes-core/rauc/rauc_1.6.bb
Labels: master, version bump, backport candidate

#192 classes: bundle: rework fetcher logic to handle dirs / subdirs etc.
  classes/bundle.bbclass
Labels: enhancement

#217 conf: layer: add 'kirkstone' to LAYERSERIES_COMPAT
  conf/layer.conf
Labels: master, kirkstone
