Repository rauc/meta-rauc, pull requests merged in 2024-01, with the labels that each got.

#295 classes-recipe: bundle: use native paths instead of target paths
  classes-recipe/bundle.bbclass
Labels: backport candidate, fix

#257 Allow Skipping Bytes from Image
  classes/bundle.bbclass
Labels: dunfell

#289 fix: bundle.bbclass: varflags expansion
  classes-recipe/bundle.bbclass
Labels: fix
