Repository rauc/meta-rauc, pull requests merged in 2024-11, with the labels that each got.

#352 bundle.bbclass: remove mentions of 'artifacts'
  classes-recipe/bundle.bbclass
Labels: documentation

#353 bundle.bbclass: extend do_bundle[file-checksums]
  classes-recipe/bundle.bbclass
Labels: master, backport candidate, fix

#357 .github/workflows/schedule-builds: Run scheduled jobs via workflow_dispatch
  .github/workflows/build.yml
  .github/workflows/schedule-builds.yml
Labels: master

#358 README: update GitHub CI badges
  README.rst
Labels: master
