Repository rauc/meta-rauc, pull requests merged in 2024-08, with the labels that each got.

#341 rauc: update to v1.12
  recipes-core/rauc/nativesdk-rauc_1.12.bb
  recipes-core/rauc/rauc-1.12.inc
  recipes-core/rauc/rauc-git.inc
  recipes-core/rauc/rauc-native_1.12.bb
  recipes-core/rauc/rauc_1.12.bb
Labels: version bump

#338 bundle.bbclass: fix hook SRC_URI example
  classes-recipe/bundle.bbclass
Labels: documentation

#345 .github/workflows/build: pre-build sstate regularly
  .github/workflows/build.yml
Labels: testing
