Repository rauc/meta-rauc, pull requests merged in 2024-04, with the labels that each got.

#306 kirkstone: rauc: update to v1.11.2
  recipes-core/rauc/nativesdk-rauc_1.11.2.bb
  recipes-core/rauc/rauc-1.11.2.inc
  recipes-core/rauc/rauc-native_1.11.2.bb
  recipes-core/rauc/rauc_1.11.2.bb
Labels: kirkstone

#307 rauc: rauc-mark-good: disable implicit dependencies
  recipes-core/rauc/files/rauc-mark-good.service
Labels: master, backport candidate, fix

#314 rauc-conf: Harmonize Installation
  recipes-core/rauc/rauc-conf.bb
Labels: clean-up
