Repository rauc/meta-rauc, pull requests merged in 2024-06, with the labels that each got.

#323 bundle.bbclass: Some Cleanups and Fixes
  classes-recipe/bundle.bbclass
Labels: backport candidate, fix, clean-up

#324 bundle.bbclass: do not generate SSTATE artifacts
  classes-recipe/bundle.bbclass
Labels: backport candidate, fix

#322 .github: workflows: meta-rauc: pin to scarthgap
  .github/workflows/meta-rauc.yml
Labels: scarthgap

#318 README.rst: remove left-over reference to tmp/deploy/tools
  README.rst
Labels: documentation

#319 README.rst: discourage to use rauc-native from DEPLOYDIR
  README.rst
Labels: documentation, kirkstone

#327 README: rauc-conf needs to be appended now instead of rauc
  README.rst
  scripts/README
Labels: documentation, backport candidate

#328 Fix typos
  README.rst
Labels: documentation
